all: false
dir: "."
filename: "pgxs_{{.InterfaceName | snakecase}}_mock.go"       # имя файла в snake_case
force-file-write: true
formatter: goimports
log-level: warn
pkgname: pgxs                                      # пакет моков будет mocks
structname: "{{.InterfaceName}}Mock"
inpackage: true
recursive: true
require-template-schema-exists: true
template: testify
template-schema: "{{.Template}}.schema.json"
packages:
  github.com/s-ilyin/pgxs:                           # ваш пакет
    config:
        all: true
  github.com/jackc/pgx/v5:
    config:
      filename: "pgx_{{.InterfaceName | snakecase}}_mock.go"
      structname: "Pgx{{.InterfaceName}}Mock"
      dir: "mocks"
      inpackage: false
      pkgname: mocks 
    interfaces:
      Tx:
      BatchResults:
      Row:
      Rows: