// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pgxs

import (
	"github.com/jackc/pgx/v5/pgxpool"
	mock "github.com/stretchr/testify/mock"
)

// NewWrapPoolMock creates a new instance of WrapPoolMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewWrapPoolMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *WrapPoolMock {
	mock := &WrapPoolMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// WrapPoolMock is an autogenerated mock type for the WrapPool type
type WrapPoolMock struct {
	mock.Mock
}

type WrapPoolMock_Expecter struct {
	mock *mock.Mock
}

func (_m *WrapPoolMock) EXPECT() *WrapPoolMock_Expecter {
	return &WrapPoolMock_Expecter{mock: &_m.Mock}
}

// Close provides a mock function for the type WrapPoolMock
func (_mock *WrapPoolMock) Close() {
	_mock.Called()
	return
}

// WrapPoolMock_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type WrapPoolMock_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *WrapPoolMock_Expecter) Close() *WrapPoolMock_Close_Call {
	return &WrapPoolMock_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *WrapPoolMock_Close_Call) Run(run func()) *WrapPoolMock_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WrapPoolMock_Close_Call) Return() *WrapPoolMock_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *WrapPoolMock_Close_Call) RunAndReturn(run func()) *WrapPoolMock_Close_Call {
	_c.Run(run)
	return _c
}

// GetPool provides a mock function for the type WrapPoolMock
func (_mock *WrapPoolMock) GetPool(shardName string) (RetryPool, error) {
	ret := _mock.Called(shardName)

	if len(ret) == 0 {
		panic("no return value specified for GetPool")
	}

	var r0 RetryPool
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (RetryPool, error)); ok {
		return returnFunc(shardName)
	}
	if returnFunc, ok := ret.Get(0).(func(string) RetryPool); ok {
		r0 = returnFunc(shardName)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(RetryPool)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(shardName)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// WrapPoolMock_GetPool_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPool'
type WrapPoolMock_GetPool_Call struct {
	*mock.Call
}

// GetPool is a helper method to define mock.On call
//   - shardName string
func (_e *WrapPoolMock_Expecter) GetPool(shardName any) *WrapPoolMock_GetPool_Call {
	return &WrapPoolMock_GetPool_Call{Call: _e.mock.On("GetPool", shardName)}
}

func (_c *WrapPoolMock_GetPool_Call) Run(run func(shardName string)) *WrapPoolMock_GetPool_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 string
		if args[0] != nil {
			arg0 = args[0].(string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *WrapPoolMock_GetPool_Call) Return(retryPool RetryPool, err error) *WrapPoolMock_GetPool_Call {
	_c.Call.Return(retryPool, err)
	return _c
}

func (_c *WrapPoolMock_GetPool_Call) RunAndReturn(run func(shardName string) (RetryPool, error)) *WrapPoolMock_GetPool_Call {
	_c.Call.Return(run)
	return _c
}

// Stats provides a mock function for the type WrapPoolMock
func (_mock *WrapPoolMock) Stats() map[string]*pgxpool.Stat {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stats")
	}

	var r0 map[string]*pgxpool.Stat
	if returnFunc, ok := ret.Get(0).(func() map[string]*pgxpool.Stat); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(map[string]*pgxpool.Stat)
		}
	}
	return r0
}

// WrapPoolMock_Stats_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stats'
type WrapPoolMock_Stats_Call struct {
	*mock.Call
}

// Stats is a helper method to define mock.On call
func (_e *WrapPoolMock_Expecter) Stats() *WrapPoolMock_Stats_Call {
	return &WrapPoolMock_Stats_Call{Call: _e.mock.On("Stats")}
}

func (_c *WrapPoolMock_Stats_Call) Run(run func()) *WrapPoolMock_Stats_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *WrapPoolMock_Stats_Call) Return(stringToStat map[string]*pgxpool.Stat) *WrapPoolMock_Stats_Call {
	_c.Call.Return(stringToStat)
	return _c
}

func (_c *WrapPoolMock_Stats_Call) RunAndReturn(run func() map[string]*pgxpool.Stat) *WrapPoolMock_Stats_Call {
	_c.Call.Return(run)
	return _c
}
