// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pgxs

import (
	mock "github.com/stretchr/testify/mock"
)

// NewPrehasherMock creates a new instance of PrehasherMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPrehasherMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PrehasherMock {
	mock := &PrehasherMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PrehasherMock is an autogenerated mock type for the Prehasher type
type PrehasherMock struct {
	mock.Mock
}

type PrehasherMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PrehasherMock) EXPECT() *PrehasherMock_Expecter {
	return &PrehasherMock_Expecter{mock: &_m.Mock}
}

// Prehash provides a mock function for the type PrehasherMock
func (_mock *PrehasherMock) Prehash() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Prehash")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// PrehasherMock_Prehash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Prehash'
type PrehasherMock_Prehash_Call struct {
	*mock.Call
}

// Prehash is a helper method to define mock.On call
func (_e *PrehasherMock_Expecter) Prehash() *PrehasherMock_Prehash_Call {
	return &PrehasherMock_Prehash_Call{Call: _e.mock.On("Prehash")}
}

func (_c *PrehasherMock_Prehash_Call) Run(run func()) *PrehasherMock_Prehash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PrehasherMock_Prehash_Call) Return(bytes []byte) *PrehasherMock_Prehash_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *PrehasherMock_Prehash_Call) RunAndReturn(run func() []byte) *PrehasherMock_Prehash_Call {
	_c.Call.Return(run)
	return _c
}
