// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pgxs

import (
	mock "github.com/stretchr/testify/mock"
)

// NewPreHasherMock creates a new instance of PreHasherMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPreHasherMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *PreHasherMock {
	mock := &PreHasherMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PreHasherMock is an autogenerated mock type for the PreHasher type
type PreHasherMock struct {
	mock.Mock
}

type PreHasherMock_Expecter struct {
	mock *mock.Mock
}

func (_m *PreHasherMock) EXPECT() *PreHasherMock_Expecter {
	return &PreHasherMock_Expecter{mock: &_m.Mock}
}

// PreHash provides a mock function for the type PreHasherMock
func (_mock *PreHasherMock) PreHash() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PreHash")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// PreHasherMock_PreHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreHash'
type PreHasherMock_PreHash_Call struct {
	*mock.Call
}

// PreHash is a helper method to define mock.On call
func (_e *PreHasherMock_Expecter) PreHash() *PreHasherMock_PreHash_Call {
	return &PreHasherMock_PreHash_Call{Call: _e.mock.On("PreHash")}
}

func (_c *PreHasherMock_PreHash_Call) Run(run func()) *PreHasherMock_PreHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PreHasherMock_PreHash_Call) Return(bytes []byte) *PreHasherMock_PreHash_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *PreHasherMock_PreHash_Call) RunAndReturn(run func() []byte) *PreHasherMock_PreHash_Call {
	_c.Call.Return(run)
	return _c
}
