// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package pgxs

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMappingMock creates a new instance of MappingMock. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMappingMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *MappingMock {
	mock := &MappingMock{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MappingMock is an autogenerated mock type for the Mapping type
type MappingMock struct {
	mock.Mock
}

type MappingMock_Expecter struct {
	mock *mock.Mock
}

func (_m *MappingMock) EXPECT() *MappingMock_Expecter {
	return &MappingMock_Expecter{mock: &_m.Mock}
}

// GetShard provides a mock function for the type MappingMock
func (_mock *MappingMock) GetShard(bucketID BucketID) (string, error) {
	ret := _mock.Called(bucketID)

	if len(ret) == 0 {
		panic("no return value specified for GetShard")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(BucketID) (string, error)); ok {
		return returnFunc(bucketID)
	}
	if returnFunc, ok := ret.Get(0).(func(BucketID) string); ok {
		r0 = returnFunc(bucketID)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(BucketID) error); ok {
		r1 = returnFunc(bucketID)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MappingMock_GetShard_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetShard'
type MappingMock_GetShard_Call struct {
	*mock.Call
}

// GetShard is a helper method to define mock.On call
//   - bucketID BucketID
func (_e *MappingMock_Expecter) GetShard(bucketID any) *MappingMock_GetShard_Call {
	return &MappingMock_GetShard_Call{Call: _e.mock.On("GetShard", bucketID)}
}

func (_c *MappingMock_GetShard_Call) Run(run func(bucketID BucketID)) *MappingMock_GetShard_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 BucketID
		if args[0] != nil {
			arg0 = args[0].(BucketID)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MappingMock_GetShard_Call) Return(s string, err error) *MappingMock_GetShard_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MappingMock_GetShard_Call) RunAndReturn(run func(bucketID BucketID) (string, error)) *MappingMock_GetShard_Call {
	_c.Call.Return(run)
	return _c
}
