// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewPreHasher creates a new instance of PreHasher. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewPreHasher(t interface {
	mock.TestingT
	Cleanup(func())
}) *PreHasher {
	mock := &PreHasher{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// PreHasher is an autogenerated mock type for the PreHasher type
type PreHasher struct {
	mock.Mock
}

type PreHasher_Expecter struct {
	mock *mock.Mock
}

func (_m *PreHasher) EXPECT() *PreHasher_Expecter {
	return &PreHasher_Expecter{mock: &_m.Mock}
}

// PreHash provides a mock function for the type PreHasher
func (_mock *PreHasher) PreHash() []byte {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for PreHash")
	}

	var r0 []byte
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	return r0
}

// PreHasher_PreHash_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'PreHash'
type PreHasher_PreHash_Call struct {
	*mock.Call
}

// PreHash is a helper method to define mock.On call
func (_e *PreHasher_Expecter) PreHash() *PreHasher_PreHash_Call {
	return &PreHasher_PreHash_Call{Call: _e.mock.On("PreHash")}
}

func (_c *PreHasher_PreHash_Call) Run(run func()) *PreHasher_PreHash_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *PreHasher_PreHash_Call) Return(bytes []byte) *PreHasher_PreHash_Call {
	_c.Call.Return(bytes)
	return _c
}

func (_c *PreHasher_PreHash_Call) RunAndReturn(run func() []byte) *PreHasher_PreHash_Call {
	_c.Call.Return(run)
	return _c
}
