// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	mock "github.com/stretchr/testify/mock"
)

// NewRetryConn creates a new instance of RetryConn. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRetryConn(t interface {
	mock.TestingT
	Cleanup(func())
}) *RetryConn {
	mock := &RetryConn{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RetryConn is an autogenerated mock type for the RetryConn type
type RetryConn struct {
	mock.Mock
}

type RetryConn_Expecter struct {
	mock *mock.Mock
}

func (_m *RetryConn) EXPECT() *RetryConn_Expecter {
	return &RetryConn_Expecter{mock: &_m.Mock}
}

// Begin provides a mock function for the type RetryConn
func (_mock *RetryConn) Begin(ctx context.Context) (pgx.Tx, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 pgx.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (pgx.Tx, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) pgx.Tx); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RetryConn_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type RetryConn_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RetryConn_Expecter) Begin(ctx any) *RetryConn_Begin_Call {
	return &RetryConn_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *RetryConn_Begin_Call) Run(run func(ctx context.Context)) *RetryConn_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RetryConn_Begin_Call) Return(tx pgx.Tx, err error) *RetryConn_Begin_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *RetryConn_Begin_Call) RunAndReturn(run func(ctx context.Context) (pgx.Tx, error)) *RetryConn_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// BeginTx provides a mock function for the type RetryConn
func (_mock *RetryConn) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	ret := _mock.Called(ctx, txOptions)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 pgx.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) (pgx.Tx, error)); ok {
		return returnFunc(ctx, txOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) pgx.Tx); ok {
		r0 = returnFunc(ctx, txOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.TxOptions) error); ok {
		r1 = returnFunc(ctx, txOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RetryConn_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type RetryConn_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - txOptions pgx.TxOptions
func (_e *RetryConn_Expecter) BeginTx(ctx any, txOptions any) *RetryConn_BeginTx_Call {
	return &RetryConn_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, txOptions)}
}

func (_c *RetryConn_BeginTx_Call) Run(run func(ctx context.Context, txOptions pgx.TxOptions)) *RetryConn_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.TxOptions
		if args[1] != nil {
			arg1 = args[1].(pgx.TxOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RetryConn_BeginTx_Call) Return(tx pgx.Tx, err error) *RetryConn_BeginTx_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *RetryConn_BeginTx_Call) RunAndReturn(run func(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error)) *RetryConn_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// Exec provides a mock function for the type RetryConn
func (_mock *RetryConn) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (pgconn.CommandTag, error)); ok {
		return returnFunc(ctx, sql, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgconn.CommandTag); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RetryConn_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type RetryConn_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *RetryConn_Expecter) Exec(ctx any, sql any, args ...any) *RetryConn_Exec_Call {
	return &RetryConn_Exec_Call{Call: _e.mock.On("Exec",
		append([]any{ctx, sql}, args...)...)}
}

func (_c *RetryConn_Exec_Call) Run(run func(ctx context.Context, sql string, args ...any)) *RetryConn_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RetryConn_Exec_Call) Return(commandTag pgconn.CommandTag, err error) *RetryConn_Exec_Call {
	_c.Call.Return(commandTag, err)
	return _c
}

func (_c *RetryConn_Exec_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)) *RetryConn_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type RetryConn
func (_mock *RetryConn) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 pgx.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (pgx.Rows, error)); ok {
		return returnFunc(ctx, sql, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Rows); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RetryConn_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type RetryConn_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *RetryConn_Expecter) Query(ctx any, sql any, args ...any) *RetryConn_Query_Call {
	return &RetryConn_Query_Call{Call: _e.mock.On("Query",
		append([]any{ctx, sql}, args...)...)}
}

func (_c *RetryConn_Query_Call) Run(run func(ctx context.Context, sql string, args ...any)) *RetryConn_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RetryConn_Query_Call) Return(rows pgx.Rows, err error) *RetryConn_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *RetryConn_Query_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) (pgx.Rows, error)) *RetryConn_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type RetryConn
func (_mock *RetryConn) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 pgx.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Row); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}
	return r0
}

// RetryConn_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type RetryConn_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *RetryConn_Expecter) QueryRow(ctx any, sql any, args ...any) *RetryConn_QueryRow_Call {
	return &RetryConn_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]any{ctx, sql}, args...)...)}
}

func (_c *RetryConn_QueryRow_Call) Run(run func(ctx context.Context, sql string, args ...any)) *RetryConn_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RetryConn_QueryRow_Call) Return(row pgx.Row) *RetryConn_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *RetryConn_QueryRow_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) pgx.Row) *RetryConn_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// Release provides a mock function for the type RetryConn
func (_mock *RetryConn) Release() {
	_mock.Called()
	return
}

// RetryConn_Release_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Release'
type RetryConn_Release_Call struct {
	*mock.Call
}

// Release is a helper method to define mock.On call
func (_e *RetryConn_Expecter) Release() *RetryConn_Release_Call {
	return &RetryConn_Release_Call{Call: _e.mock.On("Release")}
}

func (_c *RetryConn_Release_Call) Run(run func()) *RetryConn_Release_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RetryConn_Release_Call) Return() *RetryConn_Release_Call {
	_c.Call.Return()
	return _c
}

func (_c *RetryConn_Release_Call) RunAndReturn(run func()) *RetryConn_Release_Call {
	_c.Run(run)
	return _c
}

// SendBatch provides a mock function for the type RetryConn
func (_mock *RetryConn) SendBatch(ctx context.Context, batch *pgx.Batch) pgx.BatchResults {
	ret := _mock.Called(ctx, batch)

	if len(ret) == 0 {
		panic("no return value specified for SendBatch")
	}

	var r0 pgx.BatchResults
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pgx.Batch) pgx.BatchResults); ok {
		r0 = returnFunc(ctx, batch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.BatchResults)
		}
	}
	return r0
}

// RetryConn_SendBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendBatch'
type RetryConn_SendBatch_Call struct {
	*mock.Call
}

// SendBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - batch *pgx.Batch
func (_e *RetryConn_Expecter) SendBatch(ctx any, batch any) *RetryConn_SendBatch_Call {
	return &RetryConn_SendBatch_Call{Call: _e.mock.On("SendBatch", ctx, batch)}
}

func (_c *RetryConn_SendBatch_Call) Run(run func(ctx context.Context, batch *pgx.Batch)) *RetryConn_SendBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pgx.Batch
		if args[1] != nil {
			arg1 = args[1].(*pgx.Batch)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RetryConn_SendBatch_Call) Return(batchResults pgx.BatchResults) *RetryConn_SendBatch_Call {
	_c.Call.Return(batchResults)
	return _c
}

func (_c *RetryConn_SendBatch_Call) RunAndReturn(run func(ctx context.Context, batch *pgx.Batch) pgx.BatchResults) *RetryConn_SendBatch_Call {
	_c.Call.Return(run)
	return _c
}
