// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jackc/pgx/v5"
	"github.com/jackc/pgx/v5/pgconn"
	"github.com/jackc/pgx/v5/pgxpool"
	mock "github.com/stretchr/testify/mock"
)

// NewRetryPool creates a new instance of RetryPool. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewRetryPool(t interface {
	mock.TestingT
	Cleanup(func())
}) *RetryPool {
	mock := &RetryPool{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// RetryPool is an autogenerated mock type for the RetryPool type
type RetryPool struct {
	mock.Mock
}

type RetryPool_Expecter struct {
	mock *mock.Mock
}

func (_m *RetryPool) EXPECT() *RetryPool_Expecter {
	return &RetryPool_Expecter{mock: &_m.Mock}
}

// Acquire provides a mock function for the type RetryPool
func (_mock *RetryPool) Acquire(ctx context.Context) (RetryConn, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Acquire")
	}

	var r0 RetryConn
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (RetryConn, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) RetryConn); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(RetryConn)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RetryPool_Acquire_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Acquire'
type RetryPool_Acquire_Call struct {
	*mock.Call
}

// Acquire is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RetryPool_Expecter) Acquire(ctx any) *RetryPool_Acquire_Call {
	return &RetryPool_Acquire_Call{Call: _e.mock.On("Acquire", ctx)}
}

func (_c *RetryPool_Acquire_Call) Run(run func(ctx context.Context)) *RetryPool_Acquire_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RetryPool_Acquire_Call) Return(retryConn RetryConn, err error) *RetryPool_Acquire_Call {
	_c.Call.Return(retryConn, err)
	return _c
}

func (_c *RetryPool_Acquire_Call) RunAndReturn(run func(ctx context.Context) (RetryConn, error)) *RetryPool_Acquire_Call {
	_c.Call.Return(run)
	return _c
}

// Begin provides a mock function for the type RetryPool
func (_mock *RetryPool) Begin(ctx context.Context) (pgx.Tx, error) {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Begin")
	}

	var r0 pgx.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) (pgx.Tx, error)); ok {
		return returnFunc(ctx)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context) pgx.Tx); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = returnFunc(ctx)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RetryPool_Begin_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Begin'
type RetryPool_Begin_Call struct {
	*mock.Call
}

// Begin is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RetryPool_Expecter) Begin(ctx any) *RetryPool_Begin_Call {
	return &RetryPool_Begin_Call{Call: _e.mock.On("Begin", ctx)}
}

func (_c *RetryPool_Begin_Call) Run(run func(ctx context.Context)) *RetryPool_Begin_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RetryPool_Begin_Call) Return(tx pgx.Tx, err error) *RetryPool_Begin_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *RetryPool_Begin_Call) RunAndReturn(run func(ctx context.Context) (pgx.Tx, error)) *RetryPool_Begin_Call {
	_c.Call.Return(run)
	return _c
}

// BeginTx provides a mock function for the type RetryPool
func (_mock *RetryPool) BeginTx(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error) {
	ret := _mock.Called(ctx, txOptions)

	if len(ret) == 0 {
		panic("no return value specified for BeginTx")
	}

	var r0 pgx.Tx
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) (pgx.Tx, error)); ok {
		return returnFunc(ctx, txOptions)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, pgx.TxOptions) pgx.Tx); ok {
		r0 = returnFunc(ctx, txOptions)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Tx)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, pgx.TxOptions) error); ok {
		r1 = returnFunc(ctx, txOptions)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RetryPool_BeginTx_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'BeginTx'
type RetryPool_BeginTx_Call struct {
	*mock.Call
}

// BeginTx is a helper method to define mock.On call
//   - ctx context.Context
//   - txOptions pgx.TxOptions
func (_e *RetryPool_Expecter) BeginTx(ctx any, txOptions any) *RetryPool_BeginTx_Call {
	return &RetryPool_BeginTx_Call{Call: _e.mock.On("BeginTx", ctx, txOptions)}
}

func (_c *RetryPool_BeginTx_Call) Run(run func(ctx context.Context, txOptions pgx.TxOptions)) *RetryPool_BeginTx_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 pgx.TxOptions
		if args[1] != nil {
			arg1 = args[1].(pgx.TxOptions)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RetryPool_BeginTx_Call) Return(tx pgx.Tx, err error) *RetryPool_BeginTx_Call {
	_c.Call.Return(tx, err)
	return _c
}

func (_c *RetryPool_BeginTx_Call) RunAndReturn(run func(ctx context.Context, txOptions pgx.TxOptions) (pgx.Tx, error)) *RetryPool_BeginTx_Call {
	_c.Call.Return(run)
	return _c
}

// Close provides a mock function for the type RetryPool
func (_mock *RetryPool) Close() {
	_mock.Called()
	return
}

// RetryPool_Close_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Close'
type RetryPool_Close_Call struct {
	*mock.Call
}

// Close is a helper method to define mock.On call
func (_e *RetryPool_Expecter) Close() *RetryPool_Close_Call {
	return &RetryPool_Close_Call{Call: _e.mock.On("Close")}
}

func (_c *RetryPool_Close_Call) Run(run func()) *RetryPool_Close_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RetryPool_Close_Call) Return() *RetryPool_Close_Call {
	_c.Call.Return()
	return _c
}

func (_c *RetryPool_Close_Call) RunAndReturn(run func()) *RetryPool_Close_Call {
	_c.Run(run)
	return _c
}

// Exec provides a mock function for the type RetryPool
func (_mock *RetryPool) Exec(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Exec")
	}

	var r0 pgconn.CommandTag
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (pgconn.CommandTag, error)); ok {
		return returnFunc(ctx, sql, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgconn.CommandTag); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		r0 = ret.Get(0).(pgconn.CommandTag)
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RetryPool_Exec_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Exec'
type RetryPool_Exec_Call struct {
	*mock.Call
}

// Exec is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *RetryPool_Expecter) Exec(ctx any, sql any, args ...any) *RetryPool_Exec_Call {
	return &RetryPool_Exec_Call{Call: _e.mock.On("Exec",
		append([]any{ctx, sql}, args...)...)}
}

func (_c *RetryPool_Exec_Call) Run(run func(ctx context.Context, sql string, args ...any)) *RetryPool_Exec_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RetryPool_Exec_Call) Return(commandTag pgconn.CommandTag, err error) *RetryPool_Exec_Call {
	_c.Call.Return(commandTag, err)
	return _c
}

func (_c *RetryPool_Exec_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) (pgconn.CommandTag, error)) *RetryPool_Exec_Call {
	_c.Call.Return(run)
	return _c
}

// Ping provides a mock function for the type RetryPool
func (_mock *RetryPool) Ping(ctx context.Context) error {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for Ping")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = returnFunc(ctx)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// RetryPool_Ping_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Ping'
type RetryPool_Ping_Call struct {
	*mock.Call
}

// Ping is a helper method to define mock.On call
//   - ctx context.Context
func (_e *RetryPool_Expecter) Ping(ctx any) *RetryPool_Ping_Call {
	return &RetryPool_Ping_Call{Call: _e.mock.On("Ping", ctx)}
}

func (_c *RetryPool_Ping_Call) Run(run func(ctx context.Context)) *RetryPool_Ping_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *RetryPool_Ping_Call) Return(err error) *RetryPool_Ping_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *RetryPool_Ping_Call) RunAndReturn(run func(ctx context.Context) error) *RetryPool_Ping_Call {
	_c.Call.Return(run)
	return _c
}

// Query provides a mock function for the type RetryPool
func (_mock *RetryPool) Query(ctx context.Context, sql string, args ...any) (pgx.Rows, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Query")
	}

	var r0 pgx.Rows
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) (pgx.Rows, error)); ok {
		return returnFunc(ctx, sql, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Rows); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Rows)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, ...any) error); ok {
		r1 = returnFunc(ctx, sql, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// RetryPool_Query_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Query'
type RetryPool_Query_Call struct {
	*mock.Call
}

// Query is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *RetryPool_Expecter) Query(ctx any, sql any, args ...any) *RetryPool_Query_Call {
	return &RetryPool_Query_Call{Call: _e.mock.On("Query",
		append([]any{ctx, sql}, args...)...)}
}

func (_c *RetryPool_Query_Call) Run(run func(ctx context.Context, sql string, args ...any)) *RetryPool_Query_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RetryPool_Query_Call) Return(rows pgx.Rows, err error) *RetryPool_Query_Call {
	_c.Call.Return(rows, err)
	return _c
}

func (_c *RetryPool_Query_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) (pgx.Rows, error)) *RetryPool_Query_Call {
	_c.Call.Return(run)
	return _c
}

// QueryRow provides a mock function for the type RetryPool
func (_mock *RetryPool) QueryRow(ctx context.Context, sql string, args ...any) pgx.Row {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, sql, args)
	} else {
		tmpRet = _mock.Called(ctx, sql)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for QueryRow")
	}

	var r0 pgx.Row
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, ...any) pgx.Row); ok {
		r0 = returnFunc(ctx, sql, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.Row)
		}
	}
	return r0
}

// RetryPool_QueryRow_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'QueryRow'
type RetryPool_QueryRow_Call struct {
	*mock.Call
}

// QueryRow is a helper method to define mock.On call
//   - ctx context.Context
//   - sql string
//   - args ...any
func (_e *RetryPool_Expecter) QueryRow(ctx any, sql any, args ...any) *RetryPool_QueryRow_Call {
	return &RetryPool_QueryRow_Call{Call: _e.mock.On("QueryRow",
		append([]any{ctx, sql}, args...)...)}
}

func (_c *RetryPool_QueryRow_Call) Run(run func(ctx context.Context, sql string, args ...any)) *RetryPool_QueryRow_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []any
		var variadicArgs []any
		if len(args) > 2 {
			variadicArgs = args[2].([]any)
		}
		arg2 = variadicArgs
		run(
			arg0,
			arg1,
			arg2...,
		)
	})
	return _c
}

func (_c *RetryPool_QueryRow_Call) Return(row pgx.Row) *RetryPool_QueryRow_Call {
	_c.Call.Return(row)
	return _c
}

func (_c *RetryPool_QueryRow_Call) RunAndReturn(run func(ctx context.Context, sql string, args ...any) pgx.Row) *RetryPool_QueryRow_Call {
	_c.Call.Return(run)
	return _c
}

// SendBatch provides a mock function for the type RetryPool
func (_mock *RetryPool) SendBatch(ctx context.Context, batch *pgx.Batch) pgx.BatchResults {
	ret := _mock.Called(ctx, batch)

	if len(ret) == 0 {
		panic("no return value specified for SendBatch")
	}

	var r0 pgx.BatchResults
	if returnFunc, ok := ret.Get(0).(func(context.Context, *pgx.Batch) pgx.BatchResults); ok {
		r0 = returnFunc(ctx, batch)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(pgx.BatchResults)
		}
	}
	return r0
}

// RetryPool_SendBatch_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendBatch'
type RetryPool_SendBatch_Call struct {
	*mock.Call
}

// SendBatch is a helper method to define mock.On call
//   - ctx context.Context
//   - batch *pgx.Batch
func (_e *RetryPool_Expecter) SendBatch(ctx any, batch any) *RetryPool_SendBatch_Call {
	return &RetryPool_SendBatch_Call{Call: _e.mock.On("SendBatch", ctx, batch)}
}

func (_c *RetryPool_SendBatch_Call) Run(run func(ctx context.Context, batch *pgx.Batch)) *RetryPool_SendBatch_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 *pgx.Batch
		if args[1] != nil {
			arg1 = args[1].(*pgx.Batch)
		}
		run(
			arg0,
			arg1,
		)
	})
	return _c
}

func (_c *RetryPool_SendBatch_Call) Return(batchResults pgx.BatchResults) *RetryPool_SendBatch_Call {
	_c.Call.Return(batchResults)
	return _c
}

func (_c *RetryPool_SendBatch_Call) RunAndReturn(run func(ctx context.Context, batch *pgx.Batch) pgx.BatchResults) *RetryPool_SendBatch_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type RetryPool
func (_mock *RetryPool) Stat() *pgxpool.Stat {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 *pgxpool.Stat
	if returnFunc, ok := ret.Get(0).(func() *pgxpool.Stat); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*pgxpool.Stat)
		}
	}
	return r0
}

// RetryPool_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type RetryPool_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
func (_e *RetryPool_Expecter) Stat() *RetryPool_Stat_Call {
	return &RetryPool_Stat_Call{Call: _e.mock.On("Stat")}
}

func (_c *RetryPool_Stat_Call) Run(run func()) *RetryPool_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *RetryPool_Stat_Call) Return(stat *pgxpool.Stat) *RetryPool_Stat_Call {
	_c.Call.Return(stat)
	return _c
}

func (_c *RetryPool_Stat_Call) RunAndReturn(run func() *pgxpool.Stat) *RetryPool_Stat_Call {
	_c.Call.Return(run)
	return _c
}
